# Generated by Django 6.0.7 on 2026-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
