# Generated by Django 6.0.7 on 2026-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
