# Generated by Django 6.0.7 on 2026-09-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_section_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
    ]
